'''
Note: In a real environment, this file is auto-generated by running protoc. Do not write this manually. However, for the sake of the folder structure, you would include the generated output here.
Instructions to generate:
Bash
# Run this inside the 'shared' directory
python -m grpc_tools.protoc -I./schemas --python_out=./python ./schemas/events.proto
'''

"""
AUTO-GENERATED FILE. DO NOT EDIT.
Run 'protoc' to regenerate this file from shared/schemas/events.proto
"""
# Placeholder classes for typing intelligence in IDEs
class VisualFrame: pass
class MouseEvent: pass
class KeyboardEvent: pass
class A11yNode: pass
class UserInteraction: pass
class AudioChunk: pass
class AgentAction: pass
class ActionResult: pass
class BusEvent: pass

