from typing import List, Dict, Optional, Union, Any
from pydantic import BaseModel, Field
from enum import Enum
import time

# The Logic Protocol. Defines the structure of the workflow.json and training data.
# We strictly follow the schema defined in the GUI-360° paper to ensure our data is compatible with SOTA benchmarks and fine-tuning pipelines.

class ActionType(str, Enum):
    CLICK = "click"
    DOUBLE_CLICK = "double_click"
    RIGHT_CLICK = "right_click"
    TYPE = "type"
    HOTKEY = "hotkey"
    SCROLL = "scroll"
    DRAG = "drag"
    WAIT = "wait"
    CODE = "exec_code" # Agent S3 extension
    FINISHED = "finished"

class ElementMetadata(BaseModel):
    """
    Represents a UI element. 
    Can be sourced from Accessibility Tree (OS) or OmniParser (Vision).
    """
    source: str = Field(..., description="'a11y_tree' or 'omniparser_v2'")
    name: Optional[str] = None
    control_type: Optional[str] = None
    bbox: List[int] = Field(default_factory=list, description="[x1, y1, x2, y2]")
    confidence: float = 1.0

class StepAction(BaseModel):
    """
    A single executable atomic action.
    """
    function: ActionType
    arguments: Dict[str, Any] = Field(default_factory=dict)
    # Example arguments:
    # {"x": 500, "y": 200}
    # {"text": "Hello World"}
    # {"keys": ["ctrl", "c"]}
    # {"code": "import pandas..."}

# class AgentThought(BaseModel):
#     """
#     The reasoning trace (CoT) generated by Gemini/AgentS3.
#     """
#     observation: str
#     reasoning: str
#     plan: str

class ExecutionStep(BaseModel):
    """
    A full step in the workflow history.
    Compatible with GUI-360 'step' schema.
    """
    step_id: int
    timestamp: float = Field(default_factory=time.time)
    
    # Visual Context
    screenshot_path: str
    
    # Structural Context (Hybrid Parsing)
    ui_tree: Optional[Dict] = None # Full A11y Dump
    parsed_elements: Optional[List[Dict]] = None # OmniParser Output
    
    # Cognitive Trace
    thought: AgentThought
    
    # Action
    action: StepAction
    
    # Outcome
    status: str = "success" # success, failed
    error: Optional[str] = None

class Workflow(BaseModel):
    """
    The Master Plan.
    This is what the Synthesizer generates and the Executor runs.
    """
    task_id: str
    instruction: str
    app_context: str # "Excel", "Chrome", etc.
    
    parameters: List[str] = Field(default_factory=list)
    # Example: ["search_query", "destination_folder"]
    
    steps: List[ExecutionStep] = Field(default_factory=list)
    
    metadata: Dict[str, Any] = Field(default_factory=dict)

# --- Flywheel / Training Schemas ---

class FineTuningSample(BaseModel):
    """
    Format for Qwen-VL / UI-Ins SFT.
    """
    id: str
    image_path: str
    conversations: List[Dict[str, str]]
    # Example conversations:
    # [
    #   {"from": "human", "value": "<image>\nClick the Save button"},
    #   {"from": "gpt", "value": "<think>...</think><tool_call>click(100,200)</tool_call>"}
    # ]

# --- NEW: Ledger Schema from OmniTool ---
class LedgerEntry(BaseModel):
    reason: str
    answer: Union[bool, str]

class ProgressLedger(BaseModel):
    is_request_satisfied: LedgerEntry
    is_in_loop: LedgerEntry
    is_progress_being_made: LedgerEntry
    instruction_or_question: LedgerEntry

class AgentThought(BaseModel):
    observation: str
    reasoning: str
    plan: Optional[Dict[str, str]] = None  # The Orchestrator Plan
    ledger: Optional[ProgressLedger] = None # The Progress Tracker
    